# Selections

Often when we're working with numpy we're only interested in a portion of the data in our arrays. The `[]` on `ndarray` allows us select portions of the data in the array in a variety of interesting ways.

The exercises in this notebook will teach you how to select elements out of arrays in a variety of ways.

In [1]:
import numpy as np

rand = np.random.RandomState(42)  # Use a deterministic seed.

## Exercise: 1-dimensional selection

Write expressions to select the following elements from the array:

1. first element
1. second element
1. last element
1. second to last element
1. first 5 elements
1. last 5 elements
1. elements at indices 1, 4, 7, and 13
1. elements with even indices
1. the entire array, in reverse order
1. every other element, starting at index 3 (inclusive) ending at index 17 (exclusive)

In [15]:
array = np.arange(20)

In [3]:
# First Element Selection
array[0]

0

In [5]:
# Second Element Selection
array[1]

1

In [4]:
#Last Element Selection
array[-1]

19

In [8]:
# First 5 elements selection
array[:5]

array([0, 1, 2, 3, 4])

In [16]:
# Last 5 Element selection

array[-5:]

array([15, 16, 17, 18, 19])

In [28]:
# Element at given indexes

# Wanted to double check the solution hence created a new array to test it
# new_array=np.array([2,25,4,6,10,99,54,65,7,21,343,6,100,101])
index_list=[1,4,7,13]
array[index_list]
# new_array[index_list]

array([ 1,  4,  7, 13])

In [32]:
# Elements with even indices

array[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# Array in the reverse order(Both the methods are correct.Just wanted to check if numpy has an inbuilt method which can do this too)

array[::-1]
# np.lookfor("reverse")
np.flip(array,0)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [40]:
# Elements of an array with some given condition

array[3:17:2]

array([ 3,  5,  7,  9, 11, 13, 15])

In [6]:
# Second to last element selection
array[-2]

18

## Exercise: 2-dimensional selection

Write expressions to select the following elements from the array.

1. scalar value at coordinates `[3, 6]`
1. top-left scalar value
1. first row
1. first column
1. second column
1. last column
1. first 5 columns
1. last 5 columns
1. top-left 2 x 2 square
1. top-right 2 x 2 square
1. last 5 rows from every other column

In [2]:
array = np.arange(20 * 20).reshape(20, 20)
array

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

In [43]:
# Element at a given coordinate
array[(3,6)]

66

In [44]:
# Top left scalar value(0,0)
array[(0,0)]

0

In [46]:
# First Row
array[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
# First Column

array[:,0]

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240,
       260, 280, 300, 320, 340, 360, 380])

In [50]:
# Second Column

array[:,1]

array([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241,
       261, 281, 301, 321, 341, 361, 381])

In [3]:
# last Column

array[:,-1]

array([ 19,  39,  59,  79,  99, 119, 139, 159, 179, 199, 219, 239, 259,
       279, 299, 319, 339, 359, 379, 399])

In [10]:
# First 5 columns
array[:,:5]

array([[  0,   1,   2,   3,   4],
       [ 20,  21,  22,  23,  24],
       [ 40,  41,  42,  43,  44],
       [ 60,  61,  62,  63,  64],
       [ 80,  81,  82,  83,  84],
       [100, 101, 102, 103, 104],
       [120, 121, 122, 123, 124],
       [140, 141, 142, 143, 144],
       [160, 161, 162, 163, 164],
       [180, 181, 182, 183, 184],
       [200, 201, 202, 203, 204],
       [220, 221, 222, 223, 224],
       [240, 241, 242, 243, 244],
       [260, 261, 262, 263, 264],
       [280, 281, 282, 283, 284],
       [300, 301, 302, 303, 304],
       [320, 321, 322, 323, 324],
       [340, 341, 342, 343, 344],
       [360, 361, 362, 363, 364],
       [380, 381, 382, 383, 384]])

In [9]:
# last 5 columns
array[:,-5:]

array([[ 15,  16,  17,  18,  19],
       [ 35,  36,  37,  38,  39],
       [ 55,  56,  57,  58,  59],
       [ 75,  76,  77,  78,  79],
       [ 95,  96,  97,  98,  99],
       [115, 116, 117, 118, 119],
       [135, 136, 137, 138, 139],
       [155, 156, 157, 158, 159],
       [175, 176, 177, 178, 179],
       [195, 196, 197, 198, 199],
       [215, 216, 217, 218, 219],
       [235, 236, 237, 238, 239],
       [255, 256, 257, 258, 259],
       [275, 276, 277, 278, 279],
       [295, 296, 297, 298, 299],
       [315, 316, 317, 318, 319],
       [335, 336, 337, 338, 339],
       [355, 356, 357, 358, 359],
       [375, 376, 377, 378, 379],
       [395, 396, 397, 398, 399]])

In [11]:
# Top left square(first 2 rows and first 2 columns)
array[:2,:2]

array([[ 0,  1],
       [20, 21]])

In [16]:
# Top right Square (second last and last row,second last column and last column)
array[0:2,18:]

array([[18, 19],
       [38, 39]])

In [17]:
#Last 5 rows from every other column(Little Confusing while understand what exactly is required)

array[15:,::2]

array([[300, 302, 304, 306, 308, 310, 312, 314, 316, 318],
       [320, 322, 324, 326, 328, 330, 332, 334, 336, 338],
       [340, 342, 344, 346, 348, 350, 352, 354, 356, 358],
       [360, 362, 364, 366, 368, 370, 372, 374, 376, 378],
       [380, 382, 384, 386, 388, 390, 392, 394, 396, 398]])

## Exercise: N-dimensional selection

## Exercise: Selections with boolean arrays.

In [19]:
array = rand.normal(0, 1, 50)

Write an expression to select the positive values from the array.

In [20]:
# For Positive Values,use a boolean mask on the array if grater than 0
array[array>0]

array([0.49671415, 0.64768854, 1.52302986, 1.57921282, 0.76743473,
       0.54256004, 0.24196227, 0.31424733, 1.46564877, 0.0675282 ,
       0.11092259, 0.37569802, 1.85227818, 0.82254491, 0.2088636 ,
       0.19686124, 0.73846658, 0.17136828, 1.05712223, 0.34361829])

Write an expression to select the values less than -1 **or** greater than 1.5.

In [22]:
array = rand.normal(0, 1, 50)

In [26]:
# Boolean masking with or condition.Use normla or condition like in python list

array[(array<-1) | (array>1.5)]

array([-1.41537074,  1.8861859 , -1.91877122,  2.46324211, -1.16867804,
       -1.40185106,  2.19045563, -1.55066343, -1.06230371,  1.54993441,
       -1.23086432, -1.60748323, -1.23695071, -1.32045661])

Write an expression that produces the value from `array` if the value is positive, and produces the **square** of the value if it's negative.

In [29]:
array = np.arange(-5, 5)

In [31]:
# np.where?
#Use the np.where to do this.it expects 3 params.The first condition,arrayto return the data from and if the condition
# Fails then what value to return

np.where(array>1,array,array**2)

array([25, 16,  9,  4,  1,  0,  1,  2,  3,  4])

## Exercise: "FizzBuzz"

Write an expression that converts `array` into a new array of the same shape according to the following rules:

At each index `[i]`

- if `array[i]` is divisible by 3: `result[i]` should hold -1
- if `array[i]` is divisible by 5: `result[i]` should hold -2
- if `array[i]` is divisible by 15, `result[i]` should hold -3
- otherwise:`result[i]` should hold `array[i]`

(**Hint:** `np.select` works like `np.where`, but it can select from more than two arrays.)

In [62]:
array = np.arange(1, 100)

In [74]:
# ?np.select
# This can be done in multiple ways.We can also use the choose function which essentially does the same thing
conditionlist=[(array%3)==0,(array%5)==0,(((array%3)==0) & ((array%5)==0))]

choicelist=[-1,-2,-3]

np.select(conditionlist, choicelist, array)

array([[[ 1,  2, -1],
        [ 4, -2, -1],
        [ 7,  8, -1],
        [-2, 11, -1],
        [13, 14, -1],
        [16, 17, -1],
        [19, -2, -1],
        [22, 23, -1],
        [-2, 26, -1],
        [28, 29, -1],
        [31, 32, -1]],

       [[34, -2, -1],
        [37, 38, -1],
        [-2, 41, -1],
        [43, 44, -1],
        [46, 47, -1],
        [49, -2, -1],
        [52, 53, -1],
        [-2, 56, -1],
        [58, 59, -1],
        [61, 62, -1],
        [64, -2, -1]],

       [[67, 68, -1],
        [-2, 71, -1],
        [73, 74, -1],
        [76, 77, -1],
        [79, -2, -1],
        [82, 83, -1],
        [-2, 86, -1],
        [88, 89, -1],
        [91, 92, -1],
        [94, -2, -1],
        [97, 98, -1]]])

## Exercise: N-dimensional FizzBuzz

Same rules as above, but on a 3-dimensional array. (HINT: It's possible to write a solution that works for this exercise and the previous one.)

In [69]:
array = np.arange(1, 100).reshape(3, 11, 3)

In [71]:
conditionlist=[(array%3)==0,(array%5)==0,(array%15)==0]

choicelist=[-1,-2,-3]

np.select(conditionlist,choicelist,array)

array([[[ 1,  2, -1],
        [ 4, -2, -1],
        [ 7,  8, -1],
        [-2, 11, -1],
        [13, 14, -1],
        [16, 17, -1],
        [19, -2, -1],
        [22, 23, -1],
        [-2, 26, -1],
        [28, 29, -1],
        [31, 32, -1]],

       [[34, -2, -1],
        [37, 38, -1],
        [-2, 41, -1],
        [43, 44, -1],
        [46, 47, -1],
        [49, -2, -1],
        [52, 53, -1],
        [-2, 56, -1],
        [58, 59, -1],
        [61, 62, -1],
        [64, -2, -1]],

       [[67, 68, -1],
        [-2, 71, -1],
        [73, 74, -1],
        [76, 77, -1],
        [79, -2, -1],
        [82, 83, -1],
        [-2, 86, -1],
        [88, 89, -1],
        [91, 92, -1],
        [94, -2, -1],
        [97, 98, -1]]])